import pandas as pd

covid19_data = pd.read_csv('owid-covid-data.csv')
print(covid19_data)

covid19_data.keys()





covid19_data.rename(columns={'iso_code': 'ISO', 
                             'continent': 'Continent',
                            'location': 'Location',
                            'data': 'Date',
                            'total_cases': 'Total Cases',
                            'new_cases': 'New Cases',
                            'new_cases_smoothed': 'New Cases Smoothed',
                            'total_deaths': 'Total Deaths',
                            'new_deaths': 'New Deaths',
                            'new_deaths_smoothed': 'New Deaths Smoothed',
                            'total_cases_per_million': 'Total Cases Per Million',
                            'new_cases_per_million': 'New Cases Per Million', 
                            'new_cases_smoothed_per_million': 'New Cases Smoothed Per Million',
                            'total_deaths_per_million': 'Total Deaths Per Million',
                            'new_deaths_per_million': 'New Deaths Per Million',
                            'new_deaths_smoothed_per_million':'New Deaths Smoothed Per Million',
                            'reproduction_rate': 'Reproduction Rare',
                            'icu_patients': 'ICU Patients',
                            'icu_patients_per_million': 'ICU Patients Per Million', 
                            'hosp_patients': 'Hospital Patients',
                            'hosp_patients_per_million': 'Hospital Patients Per Million',
                            'weekly_icu_admissions': 'Weekly ICU Admissions',
                            'weekly_icu_admissions_per_million': 'Weekly ICU Admissions Per Million',
                            'weekly_hosp_admissions': 'Weekly Hospital Admissions', 
                            'weekly_hosp_admissions_per_million': 'Weekly Hospital Admissions Per Million',
                            'new_tests': 'New Tests',
                            'total_tests': 'Total Tests',
                            'total_tests_per_thousand': 'Total Tests Per Thousand',
                            'new_tests_per_thousand': 'New Tests Per Thousand',
                            'new_tests_smoothed': 'New Tests Smoothed',
                            'new_tests_smoothed_per_thousand': 'New Tests Smoothed Per Thousand',
                            'positive_rate': 'Positive Rate',
                            'tests_per_case': 'Tests Per Case',
                            'tests_units': 'Tests Units', 
                            'total_vaccinations': 'Total Vaccinations',
                            'people_vaccinated': 'People Vaccinated',
                            'people_fully_vaccinated': 'People Fully Vaccinated',
                            'total_boosters': 'Total Boosters',
                            'new_vaccinations': 'New Vaccinations',
                            'new_vaccinations_smoothed': 'New Vaccinations Smoothed',
                            'total_vaccinations_per_hundred': 'Total Vaccinations Per Hundred',
                            'people_vaccinated_per_hundred': 'People Vaccinated Per Hundred',
                            'people_fully_vaccinated_per_hundred': 'People Fully Vaccinated Per Hundred',
                            'total_boosters_per_hundred': 'Total Boosters Per Hundred',
                            'new_vaccinations_smoothed_per_million': 'New Vaccinations Smoothed Per Million',
                            'new_people_vaccinated_smoothed': 'New People Vaccinated Smoothed',
                            'new_people_vaccinated_smoothed_per_hundred': 'New People Vaccinated Smoothed Per Hundred',
                            'stringency_index': 'Stringency Index',
                            'population': 'Population',
                            'population_density': 'Population Density', 
                            'median_age': 'Median Age',
                            'aged_65_older': 'Aged 65 Older',
                            'aged_70_older': 'Aged 70 Older', 
                            'gdp_per_capita': 'GDP Per Capita',
                            'extreme_poverty': 'Extreme Proverty',
                            'cardiovasc_death_rate': 'Cardiovasc Death Rate', 
                            'diabetes_prevalence': 'Diabetes Prevalence',
                            'female_smokers': 'Female Smokers',
                            'male_smokers': 'Male Smokers',
                            'handwashing_facilities': 'Handwashing Facilities', 
                            'hospital_beds_per_thousand': 'Hospital Beds Per Thousand',
                            'life_expectancy': 'Life Expectancy',
                            'human_development_index': 'Human Development Index',
                            'excess_mortality_cumulative_absolute': 'Excess Mortality Cumulative Absolute',
                            'excess_mortality_cumulative': 'Excess Mortality Cumulative',
                            'excess_mortality': 'Excess Mortality', 
                            'excess_mortality_cumulative_per_million': 'Excess Mortality Cumulative Per Million']})